app/blueprints/main/models.py
from app import db, login_manager
from datetime import datetime
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(50), unique=True)
    username = db.Column(db.String(50))
    first_name = db.Column(db.String(50))
    last_name = db.Column(db.String(50))
    password = db.Column(db.String(250))
    pokemon = db.relationship('Pokemon', backref="user", lazy="dynamic")

    def hash_my_password(self, password):
        self.password = generate_password_hash(password)

    def check_my_password(self, password):
        return check_password_hash(self.password, password)

class Pokemon(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(25))
    type = db.Column(db.String(20))
    ability1 = db.Column(db.String(20))
    ability2 = db.Column(db.String(20))
    statName1 = db.Column(db.String(20))
    statValue1 = db.Column(db.Integer)
    statName2 = db.Column(db.String(20))
    statValue2 = db.Column(db.Integer)
    statName3 = db.Column(db.String(20))
    statValue3 = db.Column(db.Integer)
    weight = db.Column(db.Integer)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def get_user(self):
        return User.query.get(self.user_id)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

app/__init__.py
from flask import Flask, render_template
from config import Config
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)

    from app.blueprints.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.blueprints.api import bp as api_bp
    app.register_blueprint(api_bp)

    return app

app/blueprints/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__, url_prefix="/api/")

from . import routes

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, url_prefix="/")

from . import routes, models

app/blueprints/main/routes.py
from flask import render_template, redirect, url_for, request, flash
from . import bp as app
from app.blueprints.main.models import Pokemon
from flask_login import login_required, current_user
import requests
from app import db

my_request = requests.get('https://pokeapi.co/api/v2/pokemon/pikachu')
json_data = my_request.json()

@app.route("/")
def home():
    if not current_user.is_authenticated:
        return redirect(url_for('auth.login'))
    pokemon = Pokemon.query.all()

    pokemon.sort(key=lambda post: post.date_created, reverse=True)

    print(pokemon)

    context = {
        "pokemon": pokemon,
    }


@app.route("/usercollection")
def usercollection():
    if not current_user.is_authenticated:
        return redirect(url_for('auth.login'))
    return render_template('usercollection.html')

app/templates/addpokemon.html
{% extends './layout.html' %}

{% block content %}
<div class="container">
    <h1>Add Pokemon</h1>
    <form action="/addpokemon" method="POST">
        <div class="form-group">
          <label for="inputName">Name</label>
          <input type="name" class="form-control" name="inputName" id="inputName" aria-describedby="nameHelp">
        </div>

    </form>
</div>
{% endblock content %}

app/templates/includes/footer.html
<p>Footer</p>

app/templates/includes/header.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark mb-5">
    <a class="navbar-brand" href="#">Your Pokedex</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
        aria-expanded="false" aria-label="Toggle navigation"></button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('main.home') }}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.usercollection') }}">User Collection</a>
            </li>
        </ul>
        <ul class="navbar-nav mt-2 mt-lg-0">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

app/templates/index.html
{% extends './layout.html' %}

{% block content %}
<div class="container">
    <h1>Home</h1>
    {% if current_user.is_authenticated %}
    <p>Welcome to Pokedex, {{ current_user.username }}</p>
    <p>Here is a list of all pokemon available in the dex</p>
    <p>Try to add one by name in the form below</p>
    <div class="container">
        <h1>Add Pokemon</h1>
        <form action="/addpokemon" method="POST">
            <div class="form-group">
              <label for="inputName">Name</label>
              <input type="name" class="form-control" name="inputName" id="inputName" aria-describedby="nameHelp">
            </div>
        </form>
    </div>
    <p>Select which pokemon you would like in your personal collection</p>
    {%for i in Pokemon%}
    <div class="card w-30 mx-auto my-4 text-center">
      <div class="card-body">
        <h5 class="card-title">{{i.name}}</h5>
        <p class="card-text">{{i.sprite}}.</p>
        <p class="card-text">{{i.date_created}}.</p>
        <p class="card-text">This pokemon has {{i.ability1}} and {{i.ability2}} as starting abilities,
          a weight of {{i.weight}}, starting {{i.statName1}} of {{i.statValue1}},
          starting {{i.statName2}} of {{i.statValue2}}, and starting {{i.statName3}} of {{i.statValue3}}
        </p>
    {% endif %}
</div>
{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
</head>
<body>
    <header>
        <!-- Put the header.html file contents HERE -->
        {% include './includes/header.html' %}
    </header>
    <main>
        <!-- Import the main content here -->
        {% block content %}{% endblock content %}
    </main>
    <footer>
        <!-- Put the footer.html file contents HERE -->
        {% include './includes/footer.html' %}
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
</body>
</html>

app/templates/login.html
{% extends './layout.html' %}

{% block content %}
<div class="container">
    <h1>Login</h1>
    <form action="/auth/login" method="POST">
        <div class="form-group">
          <label for="inputEmail">Email address</label>
          <input type="email" class="form-control" name="inputEmail" id="inputEmail" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
          <label for="inputPassword">Password</label>
          <input type="password" class="form-control" name="inputPassword" id="inputPassword">
        </div>
        <p>Don't have an account? <a href="{{ url_for('auth.register') }}">Register Here.</a></p>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock content %}

app/templates/register.html
{% extends './layout.html' %}

{% block content %}
<div class="container">
    <h1>Register</h1>
    <form action="/auth/register" method="POST">
        <div class="form-group">
          <label for="inputEmail">Email address</label>
          <input type="email" class="form-control" name="inputEmail" id="inputEmail" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
          <label for="inputPassword">Password</label>
          <input type="password" class="form-control" name="inputPassword" id="inputPassword">
        </div>
        <div class="form-group">
          <label for="inputPasswordConfirm">Confirm Password</label>
          <input type="password" class="form-control" name="inputPasswordConfirm" id="inputPasswordConfirm">
        </div>
        <div class="form-group">
          <label for="inputUsername">Username</label>
          <input type="text" class="form-control" name="inputUsername" id="inputUsername">
        </div>
        <div class="form-group">
          <label for="inputFirstName">First Name</label>
          <input type="text" class="form-control" name="inputFirstName" id="inputFirstName">
        </div>
        <div class="form-group">
          <label for="inputLastName">Last Name</label>
          <input type="text" class="form-control" name="inputLastName" id="inputLastName">
        </div>
        <p>Already have an account? <a href="{{ url_for('auth.login') }}">Login Here.</a></p>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock content %}

app/templates/usercollection.html
{%extends "./layout.html"%} {%block content%}
<div class="container text-lg-center">
  <h2>{{current_user.first_name}}'s Pokedex</h2>
  <div class="container p-4">
    {%for i in current_user.pokemon%}
    <div class="card w-30 mx-auto my-4 text-center">
      <div class="card-body">
        <h5 class="card-title">{{i.name}}</h5>
        <p class="card-text">{{i.sprite}}.</p>
        <p class="card-text">{{i.date_created}}.</p>
        <p class="card-text">This pokemon has {{i.ability1}} and {{i.ability2}} as starting abilities,
          a weight of {{i.weight}}, starting {{i.statName1}} of {{i.statValue1}},
          starting {{i.statName2}} of {{i.statValue2}}, and starting {{i.statName3}} of {{i.statValue3}}
        </p>
      </div>
    </div>
    {%endfor%}
  </div>
  {%endblock content%}
</div>